"""
embed_vibe_profiles.py

Embeds every hostel's `vibe_profile` (generated by generate_vibe_profiles.py)
using Voyage AI, and writes the resulting vectors to hostel_embeddings.json.

Why a separate file instead of adding embeddings into hostels.json:
- Each embedding is 1024 floats. Inlining 228 of those into hostels.json
  would roughly triple the file size and make it painful to open/diff/read
  by hand - hostels.json is meant to stay a human-readable source of truth.
- Embeddings are a *derived* artifact (they can always be regenerated from
  vibe_profile text), so keeping them separate also makes the derivation
  relationship explicit: hostels.json -> vibe_profile -> embedding.

Voyage's `input_type="document"` is used here (as opposed to "query") -
Voyage's models are trained to expect this asymmetry: content being indexed
should be embedded as "document", while the user's search text at query time
should be embedded as "query". Using the right one on each side measurably
improves retrieval relevance. See semantic_similarity.py for the query side.

Rate limits: Voyage accounts without a payment method on file get reduced
limits (3 requests/min, 10K tokens/min) - the free 200M tokens/year for
voyage-4 still apply either way, this only affects *speed*, not cost. This
script is deliberately paced (small batches + delays) to stay under those
limits without needing a card on file. It's also resumable: progress is
saved to hostel_embeddings.json after every batch, so a Ctrl+C or a rate
limit error that exhausts retries loses at most one batch's worth of work.
"""

import os
import json
import time
from dotenv import load_dotenv
import voyageai

load_dotenv()

HOSTELS_PATH = os.path.join(os.path.dirname(__file__), "hostels.json")
EMBEDDINGS_PATH = os.path.join(os.path.dirname(__file__), "hostel_embeddings.json")
MODEL = "voyage-4"

# Tuned for the reduced (no-payment-method) rate limit: 3 requests/min, 10K tokens/min.
BATCH_SIZE = 40          # ~40 profiles * ~130 tokens avg = ~5-6K tokens/batch, safely under 10K TPM
SECONDS_BETWEEN_BATCHES = 22  # >20s ensures we never exceed 3 requests/min
MAX_RETRIES_PER_BATCH = 5
RATE_LIMIT_BACKOFF_SECONDS = 65  # a bit over a minute, to let the per-minute window reset

client = voyageai.Client(api_key=os.getenv("VOYAGE_API_KEY"))


def load_existing_embeddings():
    if os.path.exists(EMBEDDINGS_PATH):
        with open(EMBEDDINGS_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
        return data.get("embeddings", {})
    return {}


def save_embeddings(embeddings: dict):
    output = {
        "model": MODEL,
        "dim": len(next(iter(embeddings.values()))),
        "generated_from": "vibe_profile field in hostels.json",
        "count": len(embeddings),
        "embeddings": embeddings,
    }
    with open(EMBEDDINGS_PATH, "w", encoding="utf-8") as f:
        json.dump(output, f)


def embed_batch_with_retry(texts):
    for attempt in range(1, MAX_RETRIES_PER_BATCH + 1):
        try:
            return client.embed(texts, model=MODEL, input_type="document")
        except voyageai.error.RateLimitError as e:
            print(f"    rate limited (attempt {attempt}/{MAX_RETRIES_PER_BATCH}), "
                  f"backing off {RATE_LIMIT_BACKOFF_SECONDS}s...")
            time.sleep(RATE_LIMIT_BACKOFF_SECONDS)
    raise RuntimeError(f"Failed after {MAX_RETRIES_PER_BATCH} retries")


def main():
    with open(HOSTELS_PATH, "r", encoding="utf-8") as f:
        hostels = json.load(f)

    missing_profile = [h for h in hostels if not h.get("vibe_profile")]
    if missing_profile:
        print(f"WARNING: {len(missing_profile)} hostels have no vibe_profile and will be skipped:")
        for h in missing_profile:
            print(f"  id={h['id']} {h['name']!r}")

    embeddings = load_existing_embeddings()
    if embeddings:
        print(f"Resuming: {len(embeddings)} hostels already embedded from a previous run.")

    hostels_to_embed = [
        h for h in hostels
        if h.get("vibe_profile") and str(h["id"]) not in embeddings
    ]

    if not hostels_to_embed:
        print("Nothing left to embed - all hostels with a vibe_profile already have an embedding.")
        return

    print(f"Embedding {len(hostels_to_embed)} hostel vibe profiles with {MODEL} "
          f"(paced for the no-payment-method rate limit)...")

    total_tokens = 0
    num_batches = (len(hostels_to_embed) + BATCH_SIZE - 1) // BATCH_SIZE

    for batch_num, i in enumerate(range(0, len(hostels_to_embed), BATCH_SIZE), 1):
        batch = hostels_to_embed[i : i + BATCH_SIZE]
        texts = [h["vibe_profile"] for h in batch]

        result = embed_batch_with_retry(texts)
        total_tokens += result.total_tokens

        for h, vec in zip(batch, result.embeddings):
            embeddings[str(h["id"])] = vec

        save_embeddings(embeddings)  # persist after every batch

        print(f"  batch {batch_num}/{num_batches}: embedded {len(batch)} hostels "
              f"(ids {batch[0]['id']}-{batch[-1]['id']}), running total {len(embeddings)}")

        is_last_batch = (i + BATCH_SIZE) >= len(hostels_to_embed)
        if not is_last_batch:
            time.sleep(SECONDS_BETWEEN_BATCHES)

    print(f"\nDone. Embedded {len(embeddings)} hostels total.")
    print(f"Tokens used this run: {total_tokens:,} (covered by Voyage's 200M free-tokens/year tier)")
    print(f"Written to: {EMBEDDINGS_PATH}")


if __name__ == "__main__":
    main()
