"""
merge_pilot_research.py

Merges the results of the Thailand+India pilot research pass (68 hostels,
run via 14 parallel Agent subagents doing real WebSearch/WebFetch) into
hostels.json, and prints reliability stats (populated vs null per field)
for the cost/reliability estimate.

New fields added:
- services.bed_bug_reports: true|false|null  (true = credible recent report found)
- services.lockers: {"available": bool|null, "type": str|null, "note": str|null}
- services.hair_dryer_available: bool|null
- services.clothes_drying_facility: bool|null
- services.curfew_policy: str|null
- research_sources.pilot_2026_08: list of URLs used (per hostel, for audit)
- location.nearby (only for the 15 hostels that had none): same structured
  shape as normalize_nearby_and_boutique.py output, this time from genuine
  new research rather than re-reading existing text.

Not written to flagged_issues — that field already holds narrative
issue write-ups from the original research pass; these are new structured
fields alongside it, not a replacement.
"""
import json
import os

HOSTELS_PATH = os.path.join(os.path.dirname(__file__), "hostels.json")

RESULTS = [
{"id": 42, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not mentioned in listing facilities snippet or reviews found; full 26-item facility list not accessible."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "No fixed curfew; 24-hour reception, check-in window 13:00-midnight, guests asked to be quiet after 24:00.", "sources": ["https://www.hostelworld.com/st/hotels/p/293756/joey-s-hostel-agra/", "https://www.tripadvisor.com/Hotel_Review-g297683-d15701470-Reviews-Joey_s_Hostel-Agra_Agra_District_Uttar_Pradesh.html", "https://wanderlog.com/place/details/778462/joeys-hostel-agra"]},
{"id": 103, "bed_bug_reports": True, "lockers": {"available": True, "type": "in-dorm personal lockers", "note": "Listed for both female and mixed dorms on Zostel's own site."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "No stated curfew; 24/7 reception listed for all room types.", "sources": ["https://old.zostel.com/zostel/alleppey/", "https://www.tripadvisor.com/Hotel_Review-g608471-d13431012-Reviews-Zostel_Alleppey-Alappuzha_Alappuzha_District_Kerala.html", "https://www.hostelworld.com/hostels/p/285231/zostel-alleppey/"], "nearby": [{"name": "Alappuzha Beach", "type": "beach", "distance_km": 0.0, "walkable": True}, {"name": "Vijay Beach Park", "type": "landmark", "distance_km": 0.1, "walkable": True}, {"name": "Cafe Catamaran", "type": "cafe", "distance_km": 0.05, "walkable": True}, {"name": "Alleppey Backwaters / houseboat & shikara rides", "type": "nature", "distance_km": None, "walkable": True}, {"name": "Alappuzha Lighthouse", "type": "viewpoint", "distance_km": None, "walkable": None}]},
{"id": 105, "bed_bug_reports": None, "lockers": {"available": None, "type": None, "note": "No review or listing signal found on locker availability."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.lifeisoutside.com/bamboostix-island-alleppey/", "https://www.click.in/alappuzha/bamboostix-island-resort-punnamada-lake-c124-v771630", "https://www.innsite.com/inns/B236399.html"], "nearby": [{"name": "Vembanad Lake (Punnamada Lake)", "type": "nature", "distance_km": 0.0, "walkable": True}, {"name": "Punnamada Boat Jetty", "type": "landmark", "distance_km": None, "walkable": False}, {"name": "Nehru Trophy Boat Race finishing point", "type": "landmark", "distance_km": None, "walkable": None}, {"name": "Kerala backwater paddy fields", "type": "nature", "distance_km": 0.0, "walkable": True}]},
{"id": 188, "bed_bug_reports": False, "lockers": {"available": True, "type": "in-dorm lockers", "note": "Lockers provided in dorm rooms per property's own site."}, "hair_dryer_available": True, "clothes_drying_facility": None, "curfew_policy": "No curfew; 24-hour reception, with quiet/silent hours enforced 10 PM-8 AM.", "sources": ["https://www.thehosteller.com/hostels/the-hosteller-amritsar/", "https://www.tripadvisor.com/Hotel_Review-g303884-d27123125-Reviews-The_Hosteller_Amritsar_Near_Golden_Temple-Amritsar_Amritsar_District_Punjab.html", "https://www.hostelworld.com/hostels/p/324345/the-hosteller-amritsar-near-golden-temple/"]},
{"id": 35, "bed_bug_reports": False, "lockers": {"available": True, "type": "personal lockers in dorm", "note": "Reviews mention personal lockers; one review noted a locker cover net needing repair."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "No curfew; front desk staffed 24 hours.", "sources": ["https://www.goibibo.com/hotels/bunkd-hostel-anjuna-dorms-restaurant-hotel-in-goa-5992410866155955908/", "https://www.tripadvisor.com/Hotel_Review-g306992-d13354089-Reviews-Bunkd_Hostel-Anjuna_Bardez_North_Goa_District_Goa.html", "https://www.hostelworld.com/bed-and-breakfasts/p/284350/bunkd-hostels-anjuna/"]},

{"id": 36, "bed_bug_reports": None, "lockers": {"available": True, "type": "free security lockers", "note": "Listed as 'Free Security Lockers' among hostel facilities; not detailed further."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew", "sources": ["https://www.hostelworld.com/hostels/p/323244/mitra-hostel-by-the-pool/", "https://www.tripadvisor.com/Hotel_Review-g1204883-d23765930-Reviews-Mitra_Hostel_Vagator-Vagator_North_Goa_District_Goa.html"]},
{"id": 99, "bed_bug_reports": None, "lockers": {"available": None, "type": None, "note": "Lockers not explicitly mentioned in listing or reviews found."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "24-hour reception listed; no explicit curfew mentioned", "sources": ["https://www.hostelworld.com/hostels/p/322685/dreamcatcher-house-and-hostel-arambol/", "https://www.tripadvisor.com/ShowUserReviews-g2307943-d24075056-r842574843-Dreamcatcher_House_Hostel_at_Arambol_Beach-Arambol_North_Goa_District_Goa.html", "https://www.booking.com/hotel/in/dream-catcher-arambol.html"], "nearby": [{"name": "Arambol Beach", "type": "beach", "distance_km": 0.1, "walkable": True}, {"name": "Paliem Sweet Water Lake", "type": "nature", "distance_km": 1.5, "walkable": True}, {"name": "Arambol Cliff / Drum Circle sunset point", "type": "viewpoint", "distance_km": 1.0, "walkable": True}, {"name": "Arambol flea/night market", "type": "market", "distance_km": 0.5, "walkable": True}, {"name": "Mandrem Beach", "type": "beach", "distance_km": 4.5, "walkable": None}]},
{"id": 100, "bed_bug_reports": False, "lockers": {"available": True, "type": "in-dorm lockers", "note": "Guest review noted 'even the locker was soo small' - present but reported as small."}, "hair_dryer_available": None, "clothes_drying_facility": False, "curfew_policy": None, "sources": ["https://www.booking.com/hotel/in/bedrock-boutique-hostel.html", "https://www.tripadvisor.com/Hotel_Review-g635747-d15061867-Reviews-Bedrock_Boutique_Hostel-Baga_North_Goa_District_Goa.html"], "nearby": [{"name": "Baga Beach", "type": "beach", "distance_km": 0.6, "walkable": True}, {"name": "Tito's Lane", "type": "nightlife", "distance_km": 1.0, "walkable": True}, {"name": "Calangute Beach", "type": "beach", "distance_km": 2.0, "walkable": True}, {"name": "Saturday Night Market, Arpora", "type": "market", "distance_km": 3.0, "walkable": None}, {"name": "Anjuna Flea Market", "type": "market", "distance_km": 6.0, "walkable": False}]},
{"id": 183, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "General 'storage facility' mentioned on official Zostel page; dedicated lockers not explicitly confirmed."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no explicit curfew mentioned; property enforces quiet hours 11pm-6am, check-in 1pm/check-out 10am, 18+ only", "sources": ["https://www.hostelworld.com/hostels/p/323027/zostel-bangalore-koramangala/", "https://www.zostel.com/destination/bangalore/stay/zostel-bangalore-koramangala-bngh469", "https://www.booking.com/reviews/in/hotel/zostel-bangalore-koramangala.html"]},
{"id": 101, "bed_bug_reports": None, "lockers": {"available": True, "type": "in-dorm lockers", "note": "Guest review: 'Dorms have lockers (not big though) to store your valuables.'"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.tripadvisor.com/ShowUserReviews-g306995-d12920678-r618605414-Hashtag_Rooms-Calangute_North_Goa_District_Goa.html", "https://www.justdial.com/Goa/Hashtag-Rooms-Closed-Down-Calangute/0832PX832-X832-180323160009-B8D1_BZDET"], "nearby": [{"name": "Calangute Beach", "type": "beach", "distance_km": 0.1, "walkable": True}, {"name": "Baga Beach", "type": "beach", "distance_km": 2.0, "walkable": True}, {"name": "Tito's Lane", "type": "nightlife", "distance_km": 2.5, "walkable": True}, {"name": "Candolim Beach", "type": "beach", "distance_km": 3.0, "walkable": None}, {"name": "Saturday Night Market, Arpora", "type": "market", "distance_km": 4.0, "walkable": None}]},

{"id": 98, "bed_bug_reports": None, "lockers": {"available": True, "type": "in-dorm personal lockers", "note": "Reviewer noted 'separate locker to each bed'; also lockers listed in lobby/common area per listing amenities"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew", "sources": ["https://www.tripadvisor.com/Hotel_Review-g297605-d8615024-Reviews-Backpacker_Panda_Goa-Candolim_Bardez_North_Goa_District_Goa.html", "https://www.hostelz.com/hostel/279038-Backpacker-Panda---Goa", "https://www.fernhotels.com/blogs/your-guide-to-exploring-candolim-goa"], "nearby": [{"name": "Candolim Beach", "type": "beach", "distance_km": None, "walkable": True}, {"name": "Sinquerim Beach", "type": "beach", "distance_km": None, "walkable": True}, {"name": "Aguada Fort", "type": "landmark", "distance_km": None, "walkable": None}, {"name": "Candolim Church (Church of St. Lawrence)", "type": "landmark", "distance_km": None, "walkable": True}, {"name": "Calangute Beach", "type": "beach", "distance_km": None, "walkable": None}, {"name": "Baga Beach", "type": "nightlife", "distance_km": None, "walkable": None}, {"name": "SinQ Nightclub", "type": "nightlife", "distance_km": None, "walkable": None}, {"name": "Candolim Market (Tuesday market)", "type": "market", "distance_km": None, "walkable": None}]},
{"id": 23, "bed_bug_reports": None, "lockers": {"available": None, "type": "none mentioned", "note": "Facilities list did not explicitly mention lockers"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew, 24 hour reception", "sources": ["https://www.hostelworld.com/st/hostels/p/319100/backpackers-hub/", "https://www.hostelworld.com/hostels/p/319100/backpackers-hub/"]},
{"id": 8, "bed_bug_reports": None, "lockers": {"available": True, "type": "reception/free security lockers", "note": "Listing states 'Free Security Lockers' available"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew, 24 hour reception", "sources": ["https://www.hostelworld.com/hostels/p/276662/amigosindia/", "https://www.tripadvisor.com/Hotel_Review-g304551-d12528849-Reviews-Amigos_India-New_Delhi_National_Capital_Territory_of_Delhi.html", "https://amigosindia.co.in/"]},
{"id": 185, "bed_bug_reports": None, "lockers": {"available": None, "type": None, "note": "Not detailed in fetched excerpt; listing indicated 22 total facilities not all itemized"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no strict curfew, 24 hour reception", "sources": ["https://www.hostelworld.com/hostels/p/265858/zostel-gokarna/", "https://www.tripadvisor.com/Hotel_Review-g651646-d9999076-Reviews-or270-Zostel_Gokarna-Gokarna_Uttara_Kannada_District_Karnataka.html"]},
{"id": 181, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not itemized in listing facilities excerpt"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew", "sources": ["https://www.hostelworld.com/hostels/p/321681/zostel-hampi-gangavathi/", "https://www.tripadvisor.com/Hotel_Review-g319725-d26628344-Reviews-Zostel_Hampi_Gangavathi-Hampi_Bellary_District_Karnataka.html"]},

{"id": 27, "bed_bug_reports": False, "lockers": {"available": True, "type": "reception/lobby security lockers", "note": "Described as 'Free Security Lockers' and 'Lockers in Lobby' across listings; not in-dorm personal lockers."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew", "sources": ["https://www.hostelworld.com/hostels/p/303284/horn-ok-please-hostel-jaipur/", "https://www.hostelz.com/hostel/455870-Horn-Ok-Please-Hostel", "https://www.tripadvisor.com/Hotel_Review-g304555-d19622782-Reviews-Horn_Ok_Please_Hostel_Jaipur-Jaipur_Jaipur_District_Rajasthan.html"]},
{"id": 24, "bed_bug_reports": True, "lockers": {"available": True, "type": "reception/lobby security lockers", "note": "Listed as 'Security Lockers' / 'Lockers in Lobby'; not described as in-dorm."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew", "sources": ["https://www.hostelworld.com/hostels/p/317992/nomads-hostel-kasol/", "https://www.hostelz.com/hostel/356019-Nomads-Hostel", "https://www.tripadvisor.com/Hotel_Review-g2424731-d12237436-Reviews-Nomads_Hostel-Kasol_Kullu_District_Himachal_Pradesh.html"]},
{"id": 9, "bed_bug_reports": False, "lockers": {"available": True, "type": "in-dorm personal lockers (under-bed)", "note": "Hosteller's own site lists 'Individual lockers for secure storage' in dorms; one guest review requested built-in locks be added to the under-bed lockers."}, "hair_dryer_available": True, "clothes_drying_facility": None, "curfew_policy": "no curfew, 24hr reception, quiet/silent hours 10 PM - 8 AM", "sources": ["https://www.thehosteller.com/hostels/the-hosteller-fort-kochi/", "https://www.thehosteller.com/hostels/the-hosteller-fort-kochi-ocean-edge/", "https://www.hostelworld.com/hostels/p/331571/the-hosteller-fort-kochi-ocean-edge/", "https://www.tripadvisor.com/Hotel_Review-g15180821-d25050318-Reviews-The_Hosteller_Fort_Kochi-Fort_Kochi_Kochi_Cochin_Ernakulam_District_Kerala.html"]},
{"id": 20, "bed_bug_reports": None, "lockers": {"available": None, "type": None, "note": "No amenity listings or reviews mention lockers; this is a small homestay, not a typical dorm hostel."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.tripadvisor.com/Hotel_Review-g311295-d28510141-Reviews-Greenview_Homestay_Kovalam-Kovalam_Thiruvananthapuram_District_Kerala.html", "https://www.goibibo.com/hotels/greenview-homestay-hotel-in-kovalam-8315066599015704126/", "https://www.makemytrip.com/hotels/amenities-of-greenview_homestay-details-kovalam_and_poovar.html"]},
{"id": 37, "bed_bug_reports": None, "lockers": {"available": None, "type": None, "note": "Only 'Luggage Storage' is listed among popular amenities; no explicit locker mention found."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.booking.com/hotel/in/design-ashram.html", "https://www.goibibo.com/hotels/design-ashram-art-hostel-hotel-in-calicut-kozhikode-4264409446217532834/"]},

{"id": 186, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not mentioned in reviews or listing pages found."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.tripadvisor.com/Hotel_Review-g297625-d12713676-Reviews-Zostel_Leh-Leh_Leh_District_Ladakh.html", "https://www.hostelworld.com/bed-and-breakfasts/p/280302/zostel-leh/"]},
{"id": 25, "bed_bug_reports": None, "lockers": {"available": None, "type": None, "note": "Not mentioned on Hostelworld policy/facilities listing."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew (explicitly stated in property policies; check-in 12:00-23:00)", "sources": ["https://www.hostelworld.com/hostels/p/311231/farm-hostel-and-camps/", "https://www.hostelz.com/hostel/479473-FARM-Hostel---Camps", "https://www.tripadvisor.com/Hotel_Review-g297618-d23461896-Reviews-Farm_Hostel_and_Camps-Manali_Kullu_District_Himachal_Pradesh.html"]},
{"id": 184, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not mentioned; luggage storage is offered but lockers not specified."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew enforced; reception working hours 09:00-23:00", "sources": ["https://www.hostelworld.com/hostels/p/315332/zostel-mcleodganj/", "https://www.tripadvisor.in/Hotel_Review-g1092107-d24951953-Reviews-Zostel_Mcleodganj-McLeod_Ganj_Dharamsala_Kangra_District_Himachal_Pradesh.html", "https://www.hostelz.com/hostel/371292-Zostel-Dharamkot"]},
{"id": 97, "bed_bug_reports": None, "lockers": {"available": True, "type": "lockers in lobby/common area (extra paid service)", "note": "Listed as an 'extra service' alongside towels and luggage storage, not free in-dorm lockers."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.tripadvisor.com/Hotel_Review-g1936425-d5502318-Reviews-Wanderers_Hostel-Morjim_North_Goa_District_Goa.html", "https://www.hostelz.com/hostel/246245-Wanderers-Hostel"], "nearby": [{"name": "Morjim Beach", "type": "beach", "distance_km": 0.3, "walkable": True}, {"name": "Olive Ridley Turtle Nesting Site (Turtle Beach)", "type": "nature", "distance_km": 0.5, "walkable": True}, {"name": "La Plage", "type": "cafe", "distance_km": None, "walkable": True}, {"name": "Sublime", "type": "cafe", "distance_km": None, "walkable": True}, {"name": "Ashwem Beach", "type": "beach", "distance_km": 4.0, "walkable": False}, {"name": "Chapora Fort", "type": "landmark", "distance_km": 8.0, "walkable": False}, {"name": "Vagator & Anjuna nightlife area", "type": "nightlife", "distance_km": 10.0, "walkable": False}, {"name": "Sweet Water Lake, Arambol", "type": "nature", "distance_km": 6.5, "walkable": None}]},
{"id": 182, "bed_bug_reports": False, "lockers": {"available": True, "type": "in-hostel lockers plus separate luggage storage", "note": "Listed as amenities on Hostel Management/Tripadvisor listing."}, "hair_dryer_available": True, "clothes_drying_facility": True, "curfew_policy": "no curfew; 24-hour reception", "sources": ["https://www.tripadvisor.com/Hotel_Review-g304554-d13418597-Reviews-Backpacker_Panda_Colaba-Mumbai_Maharashtra.html", "https://hostelmanagement.com/india/mumbai/backpacker-panda-colaba"]},

{"id": 102, "bed_bug_reports": None, "lockers": {"available": None, "type": None, "note": None}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.hostelz.com/hostel/218515-Vedanta-Wake-Up---Munnar", "https://www.tripadvisor.in/Hotel_Review-g303881-d10210749-Reviews-Vedanta_Wake_Up_Town_Centre-Munnar_Idukki_District_Kerala.html"], "nearby": [{"name": "Munnar Tea Museum", "type": "landmark", "distance_km": 2.0, "walkable": True}, {"name": "Eravikulam National Park", "type": "nature", "distance_km": 15.0, "walkable": False}, {"name": "Mattupetty Dam", "type": "nature", "distance_km": 13.0, "walkable": False}, {"name": "Echo Point", "type": "viewpoint", "distance_km": 15.0, "walkable": False}, {"name": "Kundala Lake", "type": "nature", "distance_km": 20.0, "walkable": False}, {"name": "Attukad Waterfalls", "type": "nature", "distance_km": 12.0, "walkable": False}, {"name": "Munnar town market", "type": "market", "distance_km": None, "walkable": None}]},
{"id": 2, "bed_bug_reports": None, "lockers": {"available": True, "type": "in-dorm/security lockers (free)", "note": "Booking.com property policies list free security lockers on-site; one review mentioned mould in a room but no bed bug reports found"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew", "sources": ["https://www.booking.com/hotel/in/bunknbrew-palolem.en-gb.html", "https://www.hostelworld.com/hostels/p/313920/bunk-n-brew/"]},
{"id": 7, "bed_bug_reports": None, "lockers": {"available": None, "type": None, "note": "Not mentioned in reviews or listings found"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew", "sources": ["https://www.tripadvisor.in/Hotel_Review-g306996-d27180375-Reviews-Bibhitaki_Hostels-Canacona_South_Goa_District_Goa.html", "https://www.hostelworld.com/hostels/p/325392/bibhitaki-hostels/"]},
{"id": 34, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not mentioned in facility listings or reviews found; no bed bug complaints in extensive reviews, only mosquito mentions"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew", "sources": ["https://www.hostelworld.com/hostels/p/313113/bhakti-kutir-palolem/", "https://www.booking.com/reviews/in/hotel/bhakti-kutir.html"]},
{"id": 187, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not mentioned in reviews or on official site; substantial recent reviews with no bed bug/pest mentions"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "gates closed around midnight-1am; strict house rules (reviewers describe restrictions like no drinking after 12:30am)", "sources": ["https://www.tripadvisor.in/Hotel_Review-g659792-d15213540-Reviews-Micasa_Hostels-Pondicherry_Union_Territory_of_Pondicherry.html", "https://www.micasahostels.com/"]},

{"id": 28, "bed_bug_reports": None, "lockers": {"available": True, "type": "lobby lockers / safety deposit boxes", "note": "Planet of Hotels lists 'luggage storage and lockers' plus in-room safety deposit boxes; no in-dorm personal lockers explicitly confirmed."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "No curfew found; property has a 24-hour front desk (check-in from 12:00 PM, check-out by 11:00 AM)", "sources": ["https://www.tripadvisor.in/Hotel_Review-g319729-d21410659-Reviews-12_Monks_Hostel-Pushkar_Ajmer_District_Rajasthan.html", "https://en.planetofhotels.com/india/pushkar/12-monks-hostel-pushkar"]},
{"id": 51, "bed_bug_reports": False, "lockers": {"available": True, "type": "reception/lobby storage lockers", "note": "Official Zostel site lists 'Lockers' and 'Storage Facility' as amenities; hostelz.com lists 'Lockers in Lobby'. No mention of personal in-dorm lockers."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "No curfew found; 24/7 reception (check-in 13:00-23:00, check-out until 10:00)", "sources": ["https://www.hostelworld.com/hostels/p/101526/zostel-pushkar/", "https://www.zostel.com/destination/pushkar/stay/pushkar-rajasthan-pshx220"]},
{"id": 53, "bed_bug_reports": False, "lockers": {"available": True, "type": "conflicting reports: in-dorm lockers vs lobby lockers", "note": "dorms.com describes 'secure lockers in dorms'; hostelz.com separately describes 'Lockers in Lobby'. Availability of some form of locker is well-supported, exact type is unconfirmed."}, "hair_dryer_available": False, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.tripadvisor.com/Hotel_Review-g319729-d12268866-Reviews-Madpackers_Pushkar-Pushkar_Ajmer_District_Rajasthan.html", "https://www.hostelz.com/hostel/356399-Madpackers-Hostel"]},
{"id": 179, "bed_bug_reports": False, "lockers": {"available": True, "type": "reception/lobby storage lockers", "note": "Official Zostel site lists 'Storage facility'; hostelz.com lists 'Lockers in Lobby'. Consistent with Zostel brand pattern, no in-dorm personal lockers confirmed."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "No curfew found; check-in 13:00 (1:00 PM), check-out 10:00 AM, no stated reception cutoff", "sources": ["https://www.hostelworld.com/hostels/p/329691/zostel-rishikesh-tapovan/", "https://www.zostel.com/destination/rishikesh/stay/zostel-rishikesh-tapovan-rshh141"]},
{"id": 180, "bed_bug_reports": False, "lockers": {"available": True, "type": "lobby lockers", "note": "hostelz.com lists 'Lockers in Lobby' for this Moustache Escapes property; no in-dorm personal lockers confirmed."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "No curfew found; check-in window 12:00-23:00 (some listings note 24-hour check-in availability), check-out until 10:00", "sources": ["https://www.tripadvisor.in/Hotel_Review-g297672-d10712643-Reviews-Moustache_Hostel_Udaipur-Udaipur_Udaipur_District_Rajasthan.html", "https://www.hostelworld.com/hostels/p/269431/moustache-udaipur/"]},

{"id": 106, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not listed among Hostelworld facilities for this property (rebranded as Monkey Tribe Vagamon); no confirmation found either way."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.hostelworld.com/hostels/p/294806/monkey-tribe-vagamon/", "https://www.tripadvisor.in/Hotel_Review-g2282921-d16708521-Reviews-or10-Zostel_Vagamon-Vagamon_Idukki_District_Kerala.html"], "nearby": [{"name": "Vagamon Meadows", "type": "nature", "distance_km": None, "walkable": None}, {"name": "Pine Forest, Vagamon", "type": "nature", "distance_km": None, "walkable": None}, {"name": "Mooppanpara Viewpoint", "type": "viewpoint", "distance_km": None, "walkable": False}, {"name": "Kurisumala", "type": "landmark", "distance_km": None, "walkable": False}, {"name": "Thangal Para (Dargah shrine)", "type": "landmark", "distance_km": None, "walkable": None}, {"name": "Murugan Para Temple", "type": "landmark", "distance_km": None, "walkable": None}, {"name": "Marmala Waterfalls", "type": "nature", "distance_km": None, "walkable": False}, {"name": "Kolahalamedu Peak", "type": "viewpoint", "distance_km": None, "walkable": False}]},
{"id": 26, "bed_bug_reports": None, "lockers": {"available": True, "type": "reception storage only", "note": "One review mentions leaving belongings in a locker after checkout; review volume is very low (only ~2 detailed reviews found) so signal is weak."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.hostelz.com/hostel/479607-Gypsy-Diaries"]},
{"id": 3, "bed_bug_reports": False, "lockers": {"available": True, "type": "in-dorm personal lockers", "note": "Described as 'comfortable beds and secure lockers'; some reviews mention hygiene/cleanliness issues in common areas but no bed bug reports found."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://wanderlog.com/place/details/3833285/cliff--coral-hostel-varkala-odayam-beach", "https://www.hostelworld.com/hostels/p/304212/cliff-and-coral-varkala-odayam-beach/"]},
{"id": 21, "bed_bug_reports": False, "lockers": {"available": True, "type": "in-dorm personal lockers", "note": "Every bed has an attached locker; guests must bring or buy their own padlock. One December 2025 review mentioned finding ants/insects near a bed (not bed bugs specifically)."}, "hair_dryer_available": None, "clothes_drying_facility": True, "curfew_policy": "no curfew", "sources": ["https://www.hostelworld.com/hostels/p/313426/mollys-hostel/", "https://www.tripadvisor.com/Hotel_Review-g297639-d23849376-Reviews-Molly_s_Hostel-Varkala_Town_Varkala_Thiruvananthapuram_District_Kerala.html"]},
{"id": 38, "bed_bug_reports": False, "lockers": {"available": True, "type": "reception storage only", "note": "'No lockers in room. But there is a free locker for valuables available by the reception' per guest review. One reviewer noted windows didn't close properly, letting in mosquitoes; no bed bug mentions found."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.dorms.com/youth-Hostel/Hostal-The-Lost-Varkala-Helipad/BK2377951", "https://www.booking.com/hotel/in/the-lost-hostels-varkala-helipad.html"]},

{"id": 39, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not mentioned in hostel listings (Hostelworld, MakeMyTrip, Goibibo) or the ~578 reviews checked."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.hostelworld.com/st/hostels/p/315943/soul-varkala/"]},
{"id": 104, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not specified in listing; property emphasizes dorm/private rooms, garden, board games, foosball."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "24 hour reception, no curfew mentioned; check-in 14:00-24:00", "sources": ["https://www.hostelworld.com/hostels/p/322319/the-hosteller-wayanad-vythiri/", "https://www.tripadvisor.com/Hotel_Review-g14904550-d26774630-Reviews-The_Hosteller_Wayanad_Vythiri-Pookode_Wayanad_District_Kerala.html"], "nearby": [{"name": "Pookode Lake", "type": "nature", "distance_km": None, "walkable": True}, {"name": "Myngl Cafe (on-site)", "type": "cafe", "distance_km": 0.0, "walkable": True}, {"name": "Lakkidi Viewpoint", "type": "viewpoint", "distance_km": None, "walkable": False}, {"name": "Soochipara Falls", "type": "nature", "distance_km": None, "walkable": False}, {"name": "Edakkal Caves", "type": "landmark", "distance_km": 45.0, "walkable": False}, {"name": "Phantom Rock", "type": "viewpoint", "distance_km": None, "walkable": False}, {"name": "Thirunelli Temple", "type": "landmark", "distance_km": None, "walkable": False}]},
{"id": 31, "bed_bug_reports": True, "lockers": {"available": True, "type": "lockers in lobby (extra service)", "note": "Listed as an extra/paid service per Dorms.com/Hostelz aggregator listing."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.hostelworld.com/hostels/p/91204/amazing-backpackers-hostel-aonang/"]},
{"id": 217, "bed_bug_reports": False, "lockers": {"available": True, "type": "free security lockers / in-room lockers for valuables", "note": "Listing mentions 'free security lockers' plus in-room lockers with bunk privacy curtains."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew, reception hours 6:00 AM - 11:00 PM", "sources": ["https://www.hostelworld.com/st/hotels/p/294223/plus-hostel-ayutthaya/"]},
{"id": 29, "bed_bug_reports": None, "lockers": {"available": True, "type": "safe storage (type unspecified)", "note": "Listing mentions 'safe storage'; not specified whether in-dorm personal lockers or reception-only."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "24hr reception (24/7 front desk); no curfew mentioned", "sources": ["https://www.tripadvisor.com/Hotel_Review-g293916-d15118597-Reviews-The_Victory_View_Hostel-Bangkok.html"]},

{"id": 30, "bed_bug_reports": None, "lockers": {"available": True, "type": "in-dorm personal lockers", "note": "One Hostelworld review (Mar 2025) mentioned a broken locker lock on their bed, resolved by staff moving them."}, "hair_dryer_available": True, "clothes_drying_facility": None, "curfew_policy": "No 24hr reception; front desk staffed only 8:00 AM-10:00 PM daily, no after-hours check-in noted", "sources": ["https://www.hostelworld.com/hostels/p/286733/all-day-hostel-bts-bang-chak/"]},
{"id": 117, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not explicitly confirmed as an amenity in the sources checked, despite substantial review volume"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "No stated curfew; reception hours roughly 08:00-22:00, in-room/bar music ends at 11pm nightly (noise policy, not a lockout)", "sources": ["https://www.hostelworld.com/hostels/p/337829/nomads-bangkok-khao-san-road-hostel/", "https://nomadsworld.com/thailand/nomads-hostel-bangkok/"]},
{"id": 118, "bed_bug_reports": False, "lockers": {"available": True, "type": "lockers (in-facility security lockers per one source, lobby/luggage-area lockers per another)", "note": "Hostelworld facilities list 'Free Security Lockers'; Hostelz lists 'Lockers in Lobby' - exact in-dorm vs lobby placement unconfirmed"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "24-hour reception, no lockout; quiet time in rooms generally from 11:30pm, bar/fire pit area open later", "sources": ["https://www.hostelworld.com/hostels/p/326223/revolution-khao-san-by-the-bliss/", "https://www.hostelz.com/hostel/503559-Revolution-Khao-San-By-The-Bliss"]},
{"id": 214, "bed_bug_reports": True, "lockers": {"available": True, "type": "in-dorm personal lockers", "note": "Oyster.com review notes lockers alongside bunk beds in dorm rooms"}, "hair_dryer_available": None, "clothes_drying_facility": True, "curfew_policy": "24-hour reception (front desk staffed overnight per guest reviews); no lockout mentioned", "sources": ["https://www.hostelworld.com/hostels/p/84980/chern-hostel/", "https://www.oyster.com/bangkok/hotels/chern-hostel/"]},
{"id": 16, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not mentioned in facilities lists or reviews found"}, "hair_dryer_available": True, "clothes_drying_facility": None, "curfew_policy": "Main entrance door locked after 10 PM (keycard access still works); reception open 7 AM-10 PM, check-in until 10 PM (advance notice required for later arrivals)", "sources": ["https://www.hostelworld.com/hostels/p/305985/stay-north-gate-bed-and-breakfast/"]},

{"id": 64, "bed_bug_reports": None, "lockers": {"available": True, "type": "spacious pod-style lockers / lobby lockers", "note": "Described as 'spacious lockers' for pod dorms and 'Lockers in Lobby' as an extra service."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.hostelz.com/hostel/320819-Stamps-Backpackers", "https://stamps-backpackers.com/"]},
{"id": 87, "bed_bug_reports": True, "lockers": {"available": True, "type": "free security lockers", "note": "Booking/Hostelworld list 'Free Security Lockers'; also referenced as 'Lockers in Lobby'"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no strict curfew found; 24hr-style check-in window 14:00-23:00, one 2026 review noted noise 'stopped after 10'", "sources": ["https://www.tripadvisor.com/ShowUserReviews-g293917-d9466290-r636610489-Mad_Monkey_Chiang_Mai-Chiang_Mai.html", "https://madmonkeyhostels.com/destination/chiang-mai/"], "nearby": [{"name": "Tha Pae Gate / Old City temples", "type": "landmark", "distance_km": 1.2, "walkable": True}, {"name": "Chiang Mai Night Market / Night Bazaar", "type": "market", "distance_km": None, "walkable": True}, {"name": "Rooftop bars near Old City", "type": "nightlife", "distance_km": None, "walkable": True}, {"name": "Local cafes near Old City", "type": "cafe", "distance_km": None, "walkable": True}, {"name": "Sticky Waterfalls", "type": "nature", "distance_km": None, "walkable": False}, {"name": "Grand Canyon Water Park", "type": "nature", "distance_km": None, "walkable": False}]},
{"id": 88, "bed_bug_reports": None, "lockers": {"available": True, "type": "free/security lockers plus big under-bed lockers in dorms", "note": "Hostelworld lists 'Free Security Lockers' and 'Big size under-bed lockers' in dorm rooms"}, "hair_dryer_available": True, "clothes_drying_facility": True, "curfew_policy": "no formal curfew; reception hours 07:00-22:00, no gathering/partying in outdoor common areas (lawn/gazebo/parking) after 22:00", "sources": ["https://www.hostelworld.com/hostels/p/285374/hostel-lullaby-non-smoking/", "https://www.hostellullaby.com/"], "nearby": [{"name": "Chiang Mai Old City / Tha Pae Gate area", "type": "landmark", "distance_km": None, "walkable": None}, {"name": "Nimman / Old City cafes", "type": "cafe", "distance_km": None, "walkable": None}]},
{"id": 89, "bed_bug_reports": None, "lockers": {"available": None, "type": None, "note": "No locker information found in facility listings scanned; only general amenities like WiFi, luggage storage, 24hr reception, cable TV were listed"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no explicit curfew found; reception working hours listed as 08:00-22:00, 24hr reception also referenced on one listing (conflicting)", "sources": ["https://www.hostelworld.com/hostels/p/285980/grace-hostel/", "https://www.gracehostel.com/"], "nearby": [{"name": "Chiang Rai Clock Tower", "type": "landmark", "distance_km": 1.9, "walkable": True}, {"name": "Denha Market", "type": "market", "distance_km": None, "walkable": None}, {"name": "Oub Kham Museum", "type": "landmark", "distance_km": None, "walkable": None}, {"name": "Chiang Rai Night Bazaar", "type": "nightlife", "distance_km": None, "walkable": None}]},
{"id": 90, "bed_bug_reports": None, "lockers": {"available": True, "type": "in-room/common area lockers", "note": "Hostelworld/reviewer mention: 'lockers had plenty of room'"}, "hair_dryer_available": True, "clothes_drying_facility": None, "curfew_policy": "no explicit curfew found; reception working hours 08:00-22:00, check-in window 14:00-22:00", "sources": ["https://www.hostelworld.com/hotels/p/293134/busket-hostel/"], "nearby": [{"name": "Chiang Rai Night Bazaar", "type": "nightlife", "distance_km": 0.01, "walkable": True}, {"name": "Old Bus Station", "type": "landmark", "distance_km": 0.1, "walkable": True}, {"name": "Sirikorn Market (flower market)", "type": "market", "distance_km": 0.0, "walkable": True}, {"name": "7-Eleven", "type": "other", "distance_km": 0.25, "walkable": True}, {"name": "Cat cafe", "type": "cafe", "distance_km": 0.3, "walkable": True}, {"name": "Chiang Rai Clock Tower", "type": "landmark", "distance_km": 0.6, "walkable": True}, {"name": "Saturday Walking Street Night Market", "type": "market", "distance_km": None, "walkable": True}, {"name": "White Temple (Wat Rong Khun)", "type": "landmark", "distance_km": None, "walkable": False}]},

{"id": 91, "bed_bug_reports": False, "lockers": {"available": True, "type": "free security lockers", "note": "Listed as 'Free Security Lockers' plus free luggage storage; no locker complaints in available reviews"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "no curfew; reception working hours 8:00am-10:00pm", "sources": ["https://www.hostelworld.com/hostels/p/302424/backpack-hostel/"], "nearby": [{"name": "Chiang Rai Night Bazaar", "type": "nightlife", "distance_km": None, "walkable": True}, {"name": "Clock Tower", "type": "landmark", "distance_km": None, "walkable": True}, {"name": "Wat Rong Suea Ten (Blue Temple)", "type": "landmark", "distance_km": 3.5, "walkable": True}, {"name": "Wat Huay Pla Kang (Big Buddha)", "type": "landmark", "distance_km": 7.0, "walkable": False}, {"name": "Baan Dam Museum (Black House)", "type": "landmark", "distance_km": 10.0, "walkable": False}, {"name": "Wat Rong Khun (White Temple)", "type": "landmark", "distance_km": 13.0, "walkable": False}]},
{"id": 218, "bed_bug_reports": None, "lockers": {"available": True, "type": "lockers (property-wide, per hostel's own site)", "note": "Own website lists 'lockers' among amenities; not independently verified via third-party reviews"}, "hair_dryer_available": False, "clothes_drying_facility": True, "curfew_policy": "reception working hours 8:00-21:00 (guests arriving after 21:00 asked to notify in advance)", "sources": ["https://www.hostelworld.com/hostels/p/323587/khaosok-jungle-hostel/", "https://khaosokjunglehostel.com/"]},
{"id": 215, "bed_bug_reports": True, "lockers": {"available": None, "type": None, "note": "No locker mentions found in reviews or listing pages checked"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.tripadvisor.com/Hotel_Review-g580110-d10796581-Reviews-The_Habitat_Hostel_Koh_Chang-Ko_Chang_Trat_Province.html"]},
{"id": 212, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not mentioned on Hostelworld listing; no locker complaints or confirmations found"}, "hair_dryer_available": False, "clothes_drying_facility": True, "curfew_policy": "no curfew; reception hours 09:00-22:00 with limited access outside those hours", "sources": ["https://www.hostelworld.com/hotels/p/284018/lanta-hostel/"]},
{"id": 33, "bed_bug_reports": False, "lockers": {"available": True, "type": "lockers provided outside dorm room (key deposit 200 baht)", "note": "Confirmed by a Tripadvisor reviewer; deposit required for locker key and towel"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://www.tripadvisor.com/Hotel_Review-g11893551-d3752833-Reviews-Echo_Beach_Hostel-Baan_Tai_Ko_Pha_Ngan_Surat_Thani_Province.html"]},

{"id": 213, "bed_bug_reports": None, "lockers": {"available": True, "type": "reception storage only", "note": "Booking.com/Hostelz listing mentions 'Lockers in Lobby'; not confirmed as in-dorm personal lockers."}, "hair_dryer_available": None, "clothes_drying_facility": True, "curfew_policy": None, "sources": ["https://www.hostelz.com/hostel/485090-SocialTel-Koh-Samui"]},
{"id": 210, "bed_bug_reports": False, "lockers": {"available": True, "type": "in-dorm personal lockers", "note": "Hostelworld describes 'secure lockers' in dorm rooms; free luggage storage also offered."}, "hair_dryer_available": True, "clothes_drying_facility": None, "curfew_policy": "no curfew", "sources": ["https://www.hostelworld.com/hostels/p/270368/summer-hostel-koh-tao/"]},
{"id": 209, "bed_bug_reports": False, "lockers": {"available": True, "type": "in-dorm personal lockers", "note": "Large under-bed lockers, free of charge; guest review: 'the lockers are so big I could've put 3 times my bag in there.'"}, "hair_dryer_available": None, "clothes_drying_facility": False, "curfew_policy": "no curfew, 24hr reception", "sources": ["https://www.hostelworld.com/hostels/p/46929/pak-up-hostel/", "https://www.pakuphostel.com/"]},
{"id": 4, "bed_bug_reports": None, "lockers": {"available": None, "type": None, "note": None}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": None, "sources": ["https://hostel-sunny.paitophotels.com/es/", "https://www.booking.com/hotel/th/sunny-house-hostel.th.html"]},
{"id": 211, "bed_bug_reports": None, "lockers": {"available": None, "type": None, "note": "Listings show 'Lockers in Lobby' on one aggregator page but this could not be independently confirmed and may reflect a data error - treated as unverified."}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "informal midnight quiet-down (no strict lockout)", "sources": ["https://www.hostelworld.com/hostels/p/91394/the-famous-pai-circus-hostel/"]},

{"id": 32, "bed_bug_reports": False, "lockers": {"available": None, "type": None, "note": "Not mentioned; property is a small 20-room private-room hotel, not a dorm hostel, so in-room lockers are unlikely to apply"}, "hair_dryer_available": True, "clothes_drying_facility": None, "curfew_policy": "No curfew mentioned; reviewer notes 24-hour reception", "sources": ["https://www.tripadvisor.com/Hotel_Review-g297930-d1413341-Reviews-Hotel_Sole-Patong_Kathu_Phuket.html"]},
{"id": 17, "bed_bug_reports": False, "lockers": {"available": True, "type": "in-dorm personal lockers", "note": "Reviewers describe an extra-large locker separating each bed plus a smaller locker above for valuables"}, "hair_dryer_available": None, "clothes_drying_facility": None, "curfew_policy": "No curfew; reception hours 07:00-22:00 (late check-in requires advance notice)", "sources": ["https://www.hostelworld.com/hostels/p/314218/capzule-bed-phuket/"]},
{"id": 216, "bed_bug_reports": None, "lockers": {"available": True, "type": "lockers (listed room feature)", "note": None}, "hair_dryer_available": True, "clothes_drying_facility": True, "curfew_policy": None, "sources": ["https://www.hotels.com/ho634637632/sukhothai-cozy-hostel-dorm-sukhothai-thailand/"]},
]


def main():
    with open(HOSTELS_PATH, "r", encoding="utf-8") as f:
        hostels = json.load(f)

    by_id = {h["id"]: h for h in hostels}

    field_counts = {
        "bed_bug_reports": {"true": 0, "false": 0, "null": 0},
        "lockers_available": {"true": 0, "false": 0, "null": 0},
        "hair_dryer_available": {"true": 0, "false": 0, "null": 0},
        "clothes_drying_facility": {"true": 0, "false": 0, "null": 0},
        "curfew_policy": {"populated": 0, "null": 0},
    }
    nearby_added = 0

    for r in RESULTS:
        h = by_id.get(r["id"])
        if h is None:
            print(f"WARNING: id {r['id']} not found in hostels.json")
            continue

        services = h.setdefault("services", {})
        services["bed_bug_reports"] = r["bed_bug_reports"]
        services["lockers"] = r["lockers"]
        services["hair_dryer_available"] = r["hair_dryer_available"]
        services["clothes_drying_facility"] = r["clothes_drying_facility"]
        services["curfew_policy"] = r["curfew_policy"]

        research_sources = h.setdefault("research_sources", {})
        research_sources["pilot_2026_08_thailand_india"] = r["sources"]

        if "nearby" in r:
            h.setdefault("location", {})["nearby"] = r["nearby"]
            nearby_added += 1

        # tally reliability stats
        for field, key in [("bed_bug_reports", "bed_bug_reports")]:
            v = r[field]
            field_counts[key]["true" if v is True else "false" if v is False else "null"] += 1
        field_counts["lockers_available"]["true" if r["lockers"]["available"] is True else "false" if r["lockers"]["available"] is False else "null"] += 1
        field_counts["hair_dryer_available"]["true" if r["hair_dryer_available"] is True else "false" if r["hair_dryer_available"] is False else "null"] += 1
        field_counts["clothes_drying_facility"]["true" if r["clothes_drying_facility"] is True else "false" if r["clothes_drying_facility"] is False else "null"] += 1
        field_counts["curfew_policy"]["populated" if r["curfew_policy"] else "null"] += 1

    with open(HOSTELS_PATH, "w", encoding="utf-8") as f:
        json.dump(hostels, f, indent=2, ensure_ascii=False)

    print(f"Merged {len(RESULTS)} hostel research results.")
    print(f"New location.nearby added for {nearby_added} previously-gap hostels.\n")
    print("Field reliability (out of 68):")
    for field, counts in field_counts.items():
        print(f"  {field}: {counts}")


if __name__ == "__main__":
    main()
